### ISSUE TITLE
s/nilable produces "Cannot be a leaf without a name" errors

### ISSUE THREAD

**Issue by Velrok** [uswitch/speculate#3]
## Problem description

When transforming a value from a source spec into a destination spec `speculate.transform/transform` fails with `!!CompilerException clojure.lang.ExceptionInfo: Cannot be a leaf without a name` in cases where the destination spec describes another spec as nilable.

Minimal example:
```clojure
(do
    (s/def ::a string?)
    (s/def ::b (s/nilable ::a))

    (speculate.transform/transform ::b ::b "foo")
    ;!!CompilerException clojure.lang.ExceptionInfo: Cannot be a leaf without a name: {:type :invalid-leaf, :ast nil, :node "foo"}
    )
```

**Comment by andrewmcveigh** [comment]
Think that's the same bug that we discovered. Due to the `alpha-14` api change when referencing other specs by keyword, the spec is looked-up in place, rather than the old behaviour of leaving the keyword spec in the form.

**Comment by Velrok** [comment]
A current workaround is to simulate the `nilable` with an `or`.

```clojure
(s/def ::a string?)

; original
(s/def ::b (s/nilable ::a))

;workaround is to rewrite as or spec
(s/def ::b (s/or :nil nil?
                     :not-nil ::a))
```

**Comment by Velrok** [comment]
After failing to reproduce the issue with a test I realised that the project I was using this in was using clojure 1.9.0-alpha10.

`clojure 1.9.0-alpha14` **works**

**Comment by andrewmcveigh** [comment]
There's a fix for `(s/nilable ::something)` resolving in `alpha-15`.
